---
title: "get_gtdb_consensus_seq_stats"
author: "Sam Zimmerman"
date: "4/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/samuelzimmerman/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/prevalence")
```


```{r}
library(data.table)
global_gene_prevalence_50perc = read.table("global_conserved_genes_prevalence_by_gene_50perc.txt",sep="\t",header=T)
global_gene_prevalence_30perc = read.table("global_conserved_genes_prevalence_by_gene.txt",sep="\t",header=T)

# load gtdb data
aligned_bac120_df_50perc = read.table("../figure4_highly_conserved_genes/gtdbtk_analysis/gtdb_aligned_to_conserved_consensus_genes_50perc.txt",header=F,sep="\t")

aligned_bac120_df_30perc = read.table("../figure4_highly_conserved_genes/gtdbtk_analysis/gtdb_aligned_to_conserved_consensus_genes.txt",header=F,sep="\t")

# number of gtdb genes found
length(unique(aligned_bac120_df_50perc$V4)) # 58
length(unique(aligned_bac120_df_30perc$V4)) # 116

length(unique(aligned_bac120_df_50perc$V1)) # 104
length(unique(aligned_bac120_df_30perc$V1)) # 180

aligned_bac120_df_50perc_dt = as.data.table(aligned_bac120_df_50perc)
aligned_bac120_df_30perc_dt = as.data.table(aligned_bac120_df_30perc)

num_alignments_per_bac120gene_50perc = aligned_bac120_df_50perc_dt[,.N,by=V4]
num_alignments_per_bac120gene_30perc = aligned_bac120_df_30perc_dt[,.N,by=V4]

mean(num_alignments_per_bac120gene_50perc$N) # 3.034483
mean(num_alignments_per_bac120gene_30perc$N) # 2.051724

```

