---
title: "umap_taxa_enrichments.Rmd"
author: "Braden T Tierney"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(cowplot)
library(patchwork)
theme_set(theme_cowplot())

```

```{r}
outplots = list()
```


```{r}
#phyla

setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

cluster1 =  read.csv('cluster1_enrichments_taxa/cluster1_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster1$taxa=fct_reorder(cluster1$taxa,abs(cluster1$odds_ratio))
p1 = ggplot(cluster1,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('')  + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster1.pdf')

cluster2 =  read.csv('cluster2_enrichments_taxa/cluster2_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster2$taxa=fct_reorder(cluster2$taxa,abs(cluster2$odds_ratio))
p2= ggplot(cluster2,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster2.pdf')

cluster3 =  read.csv('cluster3_enrichments_taxa/cluster3_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster3$taxa=fct_reorder(cluster3$taxa,abs(cluster3$odds_ratio))
p3= ggplot(cluster3,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster3.pdf')

cluster4 =  read.csv('cluster4_enrichments_taxa/cluster4_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts))  %>% filter(taxa!='NA.')%>% head(10)
cluster4$taxa=fct_reorder(cluster4$taxa,abs(cluster4$odds_ratio))
p4 = ggplot(cluster4,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster4.pdf')

cluster5 =  read.csv('cluster5_enrichments_taxa/cluster5_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster5$taxa=fct_reorder(cluster5$taxa,abs(cluster5$odds_ratio))
p5 = ggplot(cluster5,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster5.pdf')

cluster6 =  read.csv('cluster6_enrichments_taxa/cluster6_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster6$taxa=fct_reorder(cluster6$taxa,abs(cluster6$odds_ratio))
p6 = ggplot(cluster6,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster6.pdf')

cluster7 =  read.csv('cluster7_enrichments_taxa/cluster7_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster7$taxa=fct_reorder(cluster7$taxa,abs(cluster7$odds_ratio))
p7 = ggplot(cluster7,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'phyla_cluster7.pdf')


```

```{r}
#class

setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

cluster1 =  read.csv('cluster1_enrichments_taxa/cluster1_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster1$taxa=fct_reorder(cluster1$taxa,abs(cluster1$odds_ratio))
g1 = ggplot(cluster1,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster1.pdf')

cluster2 =  read.csv('cluster2_enrichments_taxa/cluster2_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster2$taxa=fct_reorder(cluster2$taxa,abs(cluster2$odds_ratio))
g2 = ggplot(cluster2,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster2.pdf')

cluster3 =  read.csv('cluster3_enrichments_taxa/cluster3_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster3$taxa=fct_reorder(cluster3$taxa,abs(cluster3$odds_ratio))
g3 = ggplot(cluster3,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster3.pdf')

cluster4 =  read.csv('cluster4_enrichments_taxa/cluster4_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts))  %>% filter(taxa!='NA.')%>% head(10)
cluster4$taxa=fct_reorder(cluster4$taxa,abs(cluster4$odds_ratio))
g4 = ggplot(cluster4,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster4.pdf')

cluster5 =  read.csv('cluster5_enrichments_taxa/cluster5_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster5$taxa=fct_reorder(cluster5$taxa,abs(cluster5$odds_ratio))
g5 = ggplot(cluster5,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster5.pdf')

cluster6 =  read.csv('cluster6_enrichments_taxa/cluster6_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster6$taxa=fct_reorder(cluster6$taxa,abs(cluster6$odds_ratio))
g6 = ggplot(cluster6,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster6.pdf')

cluster7 =  read.csv('cluster7_enrichments_taxa/cluster7_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster7$taxa=fct_reorder(cluster7$taxa,abs(cluster7$odds_ratio))
g7 = ggplot(cluster7,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'class_cluster7.pdf')

```

```{r}
#genus

setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

cluster1 =  read.csv('cluster1_enrichments_taxa/cluster1_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster1$taxa=fct_reorder(cluster1$taxa,abs(cluster1$odds_ratio))
g1 = ggplot(cluster1,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster1.pdf')

cluster2 =  read.csv('cluster2_enrichments_taxa/cluster2_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster2$taxa=fct_reorder(cluster2$taxa,abs(cluster2$odds_ratio))
g2 = ggplot(cluster2,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster2.pdf')

cluster3 =  read.csv('cluster3_enrichments_taxa/cluster3_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster3$taxa=fct_reorder(cluster3$taxa,abs(cluster3$odds_ratio))
g3 = ggplot(cluster3,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster3.pdf')

cluster4 =  read.csv('cluster4_enrichments_taxa/cluster4_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts))  %>% filter(taxa!='NA.')%>% head(10)
cluster4$taxa=fct_reorder(cluster4$taxa,abs(cluster4$odds_ratio))
g4 = ggplot(cluster4,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster4.pdf')

cluster5 =  read.csv('cluster5_enrichments_taxa/cluster5_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster5$taxa=fct_reorder(cluster5$taxa,abs(cluster5$odds_ratio))
g5 = ggplot(cluster5,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster5.pdf')

cluster6 =  read.csv('cluster6_enrichments_taxa/cluster6_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster6$taxa=fct_reorder(cluster6$taxa,abs(cluster6$odds_ratio))
g6 = ggplot(cluster6,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster6.pdf')

cluster7 =  read.csv('cluster7_enrichments_taxa/cluster7_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster7$taxa=fct_reorder(cluster7$taxa,abs(cluster7$odds_ratio))
g7 = ggplot(cluster7,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'genus_cluster7.pdf')

#load phyla mapping

phyla_genus_mapping = read.csv('phyla_genus_mapping',sep='\t',header=F)



```

```{r}
#species
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

cluster1 =  read.csv('cluster1_enrichments_taxa/cluster1_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster1$taxa=fct_reorder(cluster1$taxa,abs(cluster1$odds_ratio))
s1 = ggplot(cluster1,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster1.pdf')

cluster2 =  read.csv('cluster2_enrichments_taxa/cluster2_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster2$taxa=fct_reorder(cluster2$taxa,abs(cluster2$odds_ratio))
s2 = ggplot(cluster2,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster2.pdf')

cluster3 =  read.csv('cluster3_enrichments_taxa/cluster3_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster3$taxa=fct_reorder(cluster3$taxa,abs(cluster3$odds_ratio))
s3 = ggplot(cluster3,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster3.pdf')

cluster4 =  read.csv('cluster4_enrichments_taxa/cluster4_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts))  %>% filter(taxa!='NA.')%>% head(10)
cluster4$taxa=fct_reorder(cluster4$taxa,abs(cluster4$odds_ratio))
s4= ggplot(cluster4,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster4.pdf')

cluster5 =  read.csv('cluster5_enrichments_taxa/cluster5_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster5$taxa=fct_reorder(cluster5$taxa,abs(cluster5$odds_ratio))
s5 = ggplot(cluster5,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster5.pdf')

cluster6 =  read.csv('cluster6_enrichments_taxa/cluster6_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster6$taxa=fct_reorder(cluster6$taxa,abs(cluster6$odds_ratio))
s6 = ggplot(cluster6,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster6.pdf')

cluster7 =  read.csv('cluster7_enrichments_taxa/cluster7_species_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster7$taxa=fct_reorder(cluster7$taxa,abs(cluster7$odds_ratio))
s7 = ggplot(cluster7,aes(x=taxa,y=log(odds_ratio)))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-3,8)
ggsave(width=9,height=9,'species_cluster7.pdf')

```

```{r}
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

pdf('enrichment_plots.pdf',width=16,height=16)
plot_grid(p1,g1,s1,p2,g2,s2,p3,g3,s3,p4,g4,s4,p5,g5,s5,p6,g6,s6,p7,g7,s7,ncol=3,align = 'v')
dev.off() 

```


```{r}
#genus with phyla annotation

setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

#load phyla mapping

phyla_genus_mapping = read.csv('phyla_genus_mapping',sep='\t',header=F)
colnames(phyla_genus_mapping) = c('phyla','taxa')

cluster1 =  read.csv('cluster1_enrichments_taxa/cluster1_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster1 = left_join(cluster1,phyla_genus_mapping)
cluster1$taxa=fct_reorder(cluster1$taxa,abs(cluster1$odds_ratio))
cluster1$phyla[cluster1$phyla=='Haptista'] = 'Other'
cluster1$phyla[is.na(cluster1$phyla)] = 'Other'

cluster2 =  read.csv('cluster2_enrichments_taxa/cluster2_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster2 = left_join(cluster2,phyla_genus_mapping)
cluster2$taxa=fct_reorder(cluster2$taxa,abs(cluster2$odds_ratio))

cluster3 =  read.csv('cluster3_enrichments_taxa/cluster3_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster3 = left_join(cluster3,phyla_genus_mapping)
cluster3$taxa=fct_reorder(cluster3$taxa,abs(cluster3$odds_ratio))

cluster4 =  read.csv('cluster4_enrichments_taxa/cluster4_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts))  %>% filter(taxa!='NA.')%>% head(10)
cluster4 = left_join(cluster4,phyla_genus_mapping)
cluster4$taxa=fct_reorder(cluster4$taxa,abs(cluster4$odds_ratio))

cluster5 =  read.csv('cluster5_enrichments_taxa/cluster5_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster5 = left_join(cluster5,phyla_genus_mapping)
cluster5$taxa=fct_reorder(cluster5$taxa,abs(cluster5$odds_ratio))
cluster5$phyla[is.na(cluster5$phyla)] = 'Other'

cluster6 =  read.csv('cluster6_enrichments_taxa/cluster6_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster6 = left_join(cluster6,phyla_genus_mapping)
cluster6$taxa=fct_reorder(cluster6$taxa,abs(cluster6$odds_ratio))
cluster6$phyla[is.na(cluster6$phyla)] = 'Other'
cluster6$phyla[cluster6$phyla=='Nucleocytoviricota'] = 'Other'


cluster7 =  read.csv('cluster7_enrichments_taxa/cluster7_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% arrange(desc(present_group_interest_counts)) %>% filter(taxa!='NA.') %>% head(10)
cluster7 = left_join(cluster7,phyla_genus_mapping)
cluster7$taxa=fct_reorder(cluster7$taxa,abs(cluster7$odds_ratio))


library(RColorBrewer)
colmap = bind_rows(cluster1,cluster2,cluster3,cluster4,cluster5,cluster6,cluster7) %>% select(phyla) %>% unique

myColors <- brewer.pal(12,"Set3")
names(myColors) <- levels(factor(colmap$phyla))
colScale <- scale_fill_manual(name = "phyla",values = myColors)

g1 = ggplot(cluster1,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster1_phyla_annotated.pdf')

g2 = ggplot(cluster2,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster2_phyla_annotated.pdf')

g3 = ggplot(cluster3,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster3_phyla_annotated.pdf')

g4 = ggplot(cluster4,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster4_phyla_annotated.pdf')

g5 = ggplot(cluster5,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster5_phyla_annotated.pdf')

g6 = ggplot(cluster6,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster6_phyla_annotated.pdf')

g7 = ggplot(cluster7,aes(x=taxa,y=log(odds_ratio), fill = phyla))+geom_bar(stat='identity') + geom_errorbar(aes(ymin=log(lower95_CI), ymax=log(upper95_CI)), width=.2, position=position_dodge(.9))+ coord_flip()+xlab('') + ylim(-1,8) + colScale+ theme(legend.position = "none")
ggsave(width=9,height=9,'genus_cluster7_phyla_annotated.pdf')


combined <- g1 +g2 +g3 + g4 + g5 + g6 + g7 & theme(legend.position = "bottom")

pdf('enrichment_plots_genus.pdf',width=16,height=8)
combined + plot_layout()
dev.off() 


```


```{r}
#histograms of odds ratios
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

#genus
c1g = read.csv('cluster1_enrichments_taxa/cluster1_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c2g = read.csv('cluster2_enrichments_taxa/cluster2_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c3g = read.csv('cluster3_enrichments_taxa/cluster3_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c4g = read.csv('cluster4_enrichments_taxa/cluster4_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c5g = read.csv('cluster5_enrichments_taxa/cluster5_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c6g = read.csv('cluster6_enrichments_taxa/cluster6_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c7g = read.csv('cluster7_enrichments_taxa/cluster7_genus_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 


#class
c1c = read.csv('cluster1_enrichments_taxa/cluster1_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c2c = read.csv('cluster2_enrichments_taxa/cluster2_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c3c = read.csv('cluster3_enrichments_taxa/cluster3_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c4c = read.csv('cluster4_enrichments_taxa/cluster4_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c5c = read.csv('cluster5_enrichments_taxa/cluster5_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c6c = read.csv('cluster6_enrichments_taxa/cluster6_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c7c = read.csv('cluster7_enrichments_taxa/cluster7_class_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 


#phylum
c1p = read.csv('cluster1_enrichments_taxa/cluster1_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c2p = read.csv('cluster2_enrichments_taxa/cluster2_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c3p = read.csv('cluster3_enrichments_taxa/cluster3_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c4p = read.csv('cluster4_enrichments_taxa/cluster4_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c5p = read.csv('cluster5_enrichments_taxa/cluster5_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c6p = read.csv('cluster6_enrichments_taxa/cluster6_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 
c7p = read.csv('cluster7_enrichments_taxa/cluster7_phylum_enrichemnt_enrichments.txt',sep='\t',quote="") %>% filter(fdr<0.05) %>% mutate(log_odds_ratio = log(odds_ratio)) %>% select(log_odds_ratio) 


g1 = ggplot(c1g, aes(log_odds_ratio)) +geom_histogram() + xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g2 = ggplot(c2g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g3 = ggplot(c3g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g4 = ggplot(c4g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g5 = ggplot(c5g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g6 = ggplot(c6g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)
g7 = ggplot(c7g, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,550)


c1 = ggplot(c1c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c2 = ggplot(c2c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c3 = ggplot(c3c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c4 = ggplot(c4c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c5 = ggplot(c5c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c6 = ggplot(c6c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
c7 = ggplot(c7c, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)

p1 = ggplot(c1p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p2 = ggplot(c2p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p3 = ggplot(c3p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p4 = ggplot(c4p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p5 = ggplot(c5p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p6 = ggplot(c6p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)
p7 = ggplot(c7p, aes(log_odds_ratio)) +geom_histogram()+ xlab('') + ylab('') + xlim(-10,10) +ylim(0,40)

pdf('odds_ratios_histograms_plots_taxa.pdf',width=16,height=16)
plot_grid(g1,g2,g3,g4,g5,g6,g7,c1,c2,c3,c4,c5,c6,c7,p1,p2,p3,p4,p5,p6,p7,ncol=7,align = 'v')
dev.off() 

```



##Enrichments using taxa annotations of raw genes instead of consensus genes

```{r}
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

pvals_each_cluster_each_rank = readRDS("~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/pvals_each_cluster_each_rank.rds")

pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[1]])
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})


pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[2]])
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) x %>% head(10))
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[3]])
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) x %>% head(10))
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[4]])
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) x %>% head(10))
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[5]])
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) x %>% head(10))
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[6]])
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) x %>% head(10))
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[7]])
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) x %>% head(10))
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})


species_phylum = unique(unlist(lapply(pvals_each_cluster_each_species, function(x) x$phylum)))
genus_phylum = unique(unlist(lapply(pvals_each_cluster_each_genus, function(x) x$phylum)))
class_phylum = unique(unlist(lapply(pvals_each_cluster_each_class, function(x) x$phylum)))
order_phylum = unique(unlist(lapply(pvals_each_cluster_each_order, function(x) x$phylum)))
family_phylum = unique(unlist(lapply(pvals_each_cluster_each_family, function(x) x$phylum)))
phylum_phylum = unique(unlist(lapply(pvals_each_cluster_each_phylum, function(x) x$phylum)))

unique(c(species_phylum,genus_phylum,class_phylum,order_phylum,family_phylum,phylum_phylum))

p1 = ggplot(pvals_each_cluster_each_phylum[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p2 = ggplot(pvals_each_cluster_each_phylum[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p3 = ggplot(pvals_each_cluster_each_phylum[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p4 = ggplot(pvals_each_cluster_each_phylum[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p5 = ggplot(pvals_each_cluster_each_phylum[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p6 = ggplot(pvals_each_cluster_each_phylum[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p7 = ggplot(pvals_each_cluster_each_phylum[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

c1 = ggplot(pvals_each_cluster_each_class[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c2 = ggplot(pvals_each_cluster_each_class[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c3 = ggplot(pvals_each_cluster_each_class[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c4 = ggplot(pvals_each_cluster_each_class[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c5 = ggplot(pvals_each_cluster_each_class[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c6 = ggplot(pvals_each_cluster_each_class[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c7 = ggplot(pvals_each_cluster_each_class[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

o1 = ggplot(pvals_each_cluster_each_order[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o2 = ggplot(pvals_each_cluster_each_order[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o3 = ggplot(pvals_each_cluster_each_order[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o4 = ggplot(pvals_each_cluster_each_order[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o5 = ggplot(pvals_each_cluster_each_order[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o6 = ggplot(pvals_each_cluster_each_order[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o7 = ggplot(pvals_each_cluster_each_order[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

f1 = ggplot(pvals_each_cluster_each_family[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f2 = ggplot(pvals_each_cluster_each_family[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f3 = ggplot(pvals_each_cluster_each_family[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f4 = ggplot(pvals_each_cluster_each_family[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f5 = ggplot(pvals_each_cluster_each_family[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f6 = ggplot(pvals_each_cluster_each_family[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f7 = ggplot(pvals_each_cluster_each_genus[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

g1 = ggplot(pvals_each_cluster_each_genus[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g2 = ggplot(pvals_each_cluster_each_genus[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g3 = ggplot(pvals_each_cluster_each_genus[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g4 = ggplot(pvals_each_cluster_each_genus[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g5 = ggplot(pvals_each_cluster_each_genus[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g6 = ggplot(pvals_each_cluster_each_genus[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g7 = ggplot(pvals_each_cluster_each_genus[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

s1 = ggplot(pvals_each_cluster_each_species[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s2 = ggplot(pvals_each_cluster_each_species[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s3 = ggplot(pvals_each_cluster_each_species[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s4 = ggplot(pvals_each_cluster_each_species[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s5 = ggplot(pvals_each_cluster_each_species[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s6 = ggplot(pvals_each_cluster_each_species[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s7 = ggplot(pvals_each_cluster_each_species[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2) + ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

pdf('odds_ratios_histograms_plots_taxa_revision.pdf',width=16,height=16)
plot_grid(g1,g2,g3,g4,g5,g6,g7,c1,c2,c3,c4,c5,c6,c7,p1,p2,p3,p4,p5,p6,p7,ncol=7,align = 'v')
dev.off()

ggplotList = list(g1,g2,g3,g4,g5,g6,g7,c1,c2,c3,c4,c5,c6,c7,p1,p2,p3,p4,p5,p6,p7)
names(ggplotList) = c("g1","g2","g3","g4","g5","g6","g7","c1","c2","c3","c4","c5","c6","c7","p1","p2","p3","p4","p5","p6","p7")
for(x in 1:length(ggplotList)) {
  myplot = ggplotList[[x]]
  plotname = names(ggplotList)[x]
  pdf(paste(plotname,"revision.pdf"),width=3,height=1.75)
  print(myplot)
  dev.off()
}
```

#Same thing but one sided

```{r}
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

pvals_each_cluster_each_rank = readRDS("~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/pvals_each_cluster_each_rank_onesided.rds")

pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[1]])
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_superkingdom = lapply(pvals_each_cluster_each_superkingdom, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})


pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[2]])
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) x %>% head(10))
pvals_each_cluster_each_phylum = lapply(pvals_each_cluster_each_phylum, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[3]])
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) x %>% head(10))
pvals_each_cluster_each_class = lapply(pvals_each_cluster_each_class, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[4]])
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) x %>% head(10))
pvals_each_cluster_each_order = lapply(pvals_each_cluster_each_order, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[5]])
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) x %>% head(10))
pvals_each_cluster_each_family = lapply(pvals_each_cluster_each_family, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[6]])
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) x %>% head(10))
pvals_each_cluster_each_genus = lapply(pvals_each_cluster_each_genus, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_rank, function(mylist) mylist[[7]])
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species , function(x) x %>% filter(pval<0.05) %>% mutate(log_odds_ratio = log(odds_ratio),log_CI=log(CI),log_upper_95=log(upper95_CI),log_lower95_CI=log(lower95_CI))) 
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) x %>% arrange(pval,desc(abs(odds_ratio))))
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) x %>% head(10))
pvals_each_cluster_each_species = lapply(pvals_each_cluster_each_species, function(x) {
  x$taxa = factor(x$taxa,levels=x$taxa)
  return(x)
})


species_phylum = unique(unlist(lapply(pvals_each_cluster_each_species, function(x) x$phylum)))
genus_phylum = unique(unlist(lapply(pvals_each_cluster_each_genus, function(x) x$phylum)))
class_phylum = unique(unlist(lapply(pvals_each_cluster_each_class, function(x) x$phylum)))
order_phylum = unique(unlist(lapply(pvals_each_cluster_each_order, function(x) x$phylum)))
family_phylum = unique(unlist(lapply(pvals_each_cluster_each_family, function(x) x$phylum)))
phylum_phylum = unique(unlist(lapply(pvals_each_cluster_each_phylum, function(x) x$phylum)))

unique(c(species_phylum,genus_phylum,class_phylum,order_phylum,family_phylum,phylum_phylum))

p1 = ggplot(pvals_each_cluster_each_phylum[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p2 = ggplot(pvals_each_cluster_each_phylum[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p3 = ggplot(pvals_each_cluster_each_phylum[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p4 = ggplot(pvals_each_cluster_each_phylum[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p5 = ggplot(pvals_each_cluster_each_phylum[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p6 = ggplot(pvals_each_cluster_each_phylum[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p7 = ggplot(pvals_each_cluster_each_phylum[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

c1 = ggplot(pvals_each_cluster_each_class[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c2 = ggplot(pvals_each_cluster_each_class[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c3 = ggplot(pvals_each_cluster_each_class[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c4 = ggplot(pvals_each_cluster_each_class[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c5 = ggplot(pvals_each_cluster_each_class[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c6 = ggplot(pvals_each_cluster_each_class[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c7 = ggplot(pvals_each_cluster_each_class[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

o1 = ggplot(pvals_each_cluster_each_order[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o2 = ggplot(pvals_each_cluster_each_order[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o3 = ggplot(pvals_each_cluster_each_order[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o4 = ggplot(pvals_each_cluster_each_order[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o5 = ggplot(pvals_each_cluster_each_order[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o6 = ggplot(pvals_each_cluster_each_order[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o7 = ggplot(pvals_each_cluster_each_order[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

f1 = ggplot(pvals_each_cluster_each_family[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f2 = ggplot(pvals_each_cluster_each_family[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f3 = ggplot(pvals_each_cluster_each_family[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f4 = ggplot(pvals_each_cluster_each_family[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f5 = ggplot(pvals_each_cluster_each_family[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f6 = ggplot(pvals_each_cluster_each_family[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f7 = ggplot(pvals_each_cluster_each_genus[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

g1 = ggplot(pvals_each_cluster_each_genus[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g2 = ggplot(pvals_each_cluster_each_genus[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g3 = ggplot(pvals_each_cluster_each_genus[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g4 = ggplot(pvals_each_cluster_each_genus[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g5 = ggplot(pvals_each_cluster_each_genus[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g6 = ggplot(pvals_each_cluster_each_genus[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g7 = ggplot(pvals_each_cluster_each_genus[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

s1 = ggplot(pvals_each_cluster_each_species[[2]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s2 = ggplot(pvals_each_cluster_each_species[[3]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s3 = ggplot(pvals_each_cluster_each_species[[4]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s4 = ggplot(pvals_each_cluster_each_species[[5]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s5 = ggplot(pvals_each_cluster_each_species[[6]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s6 = ggplot(pvals_each_cluster_each_species[[7]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2)+ ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s7 = ggplot(pvals_each_cluster_each_species[[8]],aes(x=taxa,y=log_odds_ratio)) + geom_bar(stat="identity") + coord_flip() + geom_errorbar(aes(ymin=log_lower95_CI, ymax=log_upper_95), width=.2) + ylab("") + xlab("") + scale_y_continuous(limits = c(-8, 9)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

ggplotList = list(g1,g2,g3,g4,g5,g6,g7,c1,c2,c3,c4,c5,c6,c7,p1,p2,p3,p4,p5,p6,p7)
names(ggplotList) = c("g1","g2","g3","g4","g5","g6","g7","c1","c2","c3","c4","c5","c6","c7","p1","p2","p3","p4","p5","p6","p7")
for(x in 1:length(ggplotList)) {
  myplot = ggplotList[[x]]
  plotname = names(ggplotList)[x]
  pdf(paste(plotname,"_one_sided_revision.pdf"),width=3,height=1.75)
  print(myplot)
  dev.off()
}

```

##Do another version where I use the results from ttest instead of fishers exact test with the raw genes

```{r}
library(dplyr)
setwd('~/Dropbox (HMS)/Kostic_Lab/datasets/orfletonV2/complete_linkage_analysis/UMAP_enrichment3_BY/')

#put all pvalues in single document for figshare

prep_doc_figshare = function(rdsfile,taxa_level) {
  ttest_res_class = readRDS(rdsfile)
  ttest_res_class = lapply(ttest_res_class, as.data.frame)
  ttest_res_class2 = list()
  for(mycount in 1:length(ttest_res_class)) {
     x = ttest_res_class[[mycount]]
     x$logFC = log2(x$fold_change)
     if(taxa_level == "phylum" | taxa_level == "superkingdom") {
       x$taxa = rownames(x)
       x$phylum = rownames(x)
     } else {
       x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
       x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
     }
     x$cluster = mycount
     x$taxa_level = taxa_level
     x = x[order(x$pvalue),]
     ttest_res_class2[[mycount]] = x
  }
  ttest_res_class2 = do.call("rbind",ttest_res_class2)
  return(ttest_res_class2)
}

class_df = prep_doc_figshare(rdsfile="ttest_res_class.rds",taxa_level="class")
family_df = prep_doc_figshare(rdsfile="ttest_res_family.rds",taxa_level="family")
genus_df = prep_doc_figshare(rdsfile="ttest_res_genus.rds",taxa_level="genus")
species_df = prep_doc_figshare(rdsfile="ttest_res_species.rds",taxa_level="species")
phylum_df = prep_doc_figshare(rdsfile="ttest_res_phylum.rds",taxa_level="phylum")
superkingdom_df = prep_doc_figshare(rdsfile="ttest_res_superkingdom.rds",taxa_level="superkingdom")

all_enrichment_pvals_df = rbind(superkingdom_df,phylum_df,class_df,family_df,genus_df,species_df)
write.csv(all_enrichment_pvals_df,"taxa_enrichment_table_all_clusters_revised.csv")


ttest_res_class = readRDS("ttest_res_class.rds")
ttest_res_class = lapply(ttest_res_class, as.data.frame)
ttest_res_class2 = list()
for(mycount in 1:length(ttest_res_class)) {
  x = ttest_res_class[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
  x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_class2[[mycount]] = x
}

ttest_res_family = readRDS("ttest_res_family.rds")
ttest_res_family = lapply(ttest_res_family, as.data.frame)
ttest_res_family2 = list()
for(mycount in 1:length(ttest_res_family)) {
  x = ttest_res_family[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
  x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_family2[[mycount]] = x
}

ttest_res_genus = readRDS("ttest_res_genus.rds")
ttest_res_genus = lapply(ttest_res_genus, as.data.frame)
ttest_res_genus2 = list()
all_phylums_per_enriched_genus = c()
for(mycount in 1:length(ttest_res_genus)) {
  x = ttest_res_genus[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
  x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_genus2[[mycount]] = x
  all_phylums_per_enriched_genus = c(all_phylums_per_enriched_genus,unique(x$phylum[1:10]))
}
all_phylums_per_enriched_genus = unique(all_phylums_per_enriched_genus)
all_phylums_per_enriched_genus = all_phylums_per_enriched_genus[!is.na(all_phylums_per_enriched_genus)]

ttest_res_order = readRDS("ttest_res_order.rds")
ttest_res_order = lapply(ttest_res_order, as.data.frame)
ttest_res_order2 = list()
for(mycount in 1:length(ttest_res_order)) {
  x = ttest_res_order[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
  x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_order2[[mycount]] = x
}

ttest_res_species = readRDS("ttest_res_species.rds")
ttest_res_species = lapply(ttest_res_species, as.data.frame)
ttest_res_species2 = list()
for(mycount in 1:length(ttest_res_species)) {
  x = ttest_res_species[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$phylum = sapply(strsplit(rownames(x),split="_"), function(y) y[length(y)])
  x$taxa = sapply(strsplit(rownames(x),split="_"), function(y) paste(y[-length(y)],collapse="_"))
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_species2[[mycount]] = x
}

ttest_res_phylum = readRDS("ttest_res_phylum.rds")
ttest_res_phylum = lapply(ttest_res_phylum, as.data.frame)
ttest_res_phylum2 = list()
for(mycount in 1:length(ttest_res_phylum)) {
  x = ttest_res_phylum[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$taxa = rownames(x)
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_phylum2[[mycount]] = x
}

ttest_res_superkingdom = readRDS("ttest_res_superkingdom.rds")
ttest_res_superkingdom = lapply(ttest_res_superkingdom, as.data.frame)
ttest_res_superkingdom2 = list()
for(mycount in 1:length(ttest_res_superkingdom)) {
  x = ttest_res_superkingdom[[mycount]]
  x$logFC = log2(x$fold_change)
  x = x %>% filter(BY<0.05) %>% arrange(pvalue,desc(abs(logFC)))
  x$taxa = rownames(x)
  x$taxa = factor(x$taxa,levels=x$taxa)
  ttest_res_superkingdom2[[mycount]] = x
}


c1 = ttest_res_class2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c2 = ttest_res_class2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c3 = ttest_res_class2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c4 = ttest_res_class2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c5 = ttest_res_class2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c6 = ttest_res_class2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
c7 = ttest_res_class2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))


p1 = ttest_res_phylum2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p2 = ttest_res_phylum2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p3 = ttest_res_phylum2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p4 = ttest_res_phylum2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p5 = ttest_res_phylum2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p6 = ttest_res_phylum2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
p7 = ttest_res_phylum2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

o1 = ttest_res_order2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o2 = ttest_res_order2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o3 = ttest_res_order2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o4 = ttest_res_order2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o5 = ttest_res_order2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o6 = ttest_res_order2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
o7 = ttest_res_order2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))


f1 = ttest_res_family2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f2 = ttest_res_family2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f3 = ttest_res_family2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f4 = ttest_res_family2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f5 = ttest_res_family2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f6 = ttest_res_family2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
f7 = ttest_res_family2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

g1 = ttest_res_genus2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g2 = ttest_res_genus2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g3 = ttest_res_genus2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g4 = ttest_res_genus2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g5 = ttest_res_genus2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g6 = ttest_res_genus2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
g7 = ttest_res_genus2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))

write.csv(ttest_res_genus2[[3]],file="ttest_res_genus2.csv")

s1 = ttest_res_species2[[1]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s2 = ttest_res_species2[[2]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s3 = ttest_res_species2[[3]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s4 = ttest_res_species2[[4]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s5 = ttest_res_species2[[5]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s6 = ttest_res_species2[[6]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))
s7 = ttest_res_species2[[7]] %>% head(10) %>% ggplot(aes(x=taxa,y=logFC)) + geom_bar(stat="identity") + theme_classic() + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme(axis.text.x = element_text(size=2), axis.text.y = element_text(size=7))



ggplotList = list(g1,g2,g3,g4,g5,g6,g7,c1,c2,c3,c4,c5,c6,c7,p1,p2,p3,p4,p5,p6,p7)
names(ggplotList) = c("g1","g2","g3","g4","g5","g6","g7","c1","c2","c3","c4","c5","c6","c7","p1","p2","p3","p4","p5","p6","p7")
for(x in 1:length(ggplotList)) {
  myplot = ggplotList[[x]]
  plotname = names(ggplotList)[x]
  pdf(paste(plotname,"_one_sided_revision_ttest_res.pdf"),width=3,height=1.75)
  print(myplot)
  dev.off()
}

my_colors = pals::alphabet(length(all_phylums_per_enriched_genus))
names(my_colors) = all_phylums_per_enriched_genus

pdf("genus_cluster1_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust1_top10 = ttest_res_genus2[[1]] %>% head(10)
ttest_res_genus2_clust1_top10$phylum = factor(ttest_res_genus2_clust1_top10$phylum,levels=all_phylums_per_enriched_genus)
g1_colored = ttest_res_genus2_clust1_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=5)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g1_colored)
dev.off()
pdf("genus_cluster2_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust2_top10 = ttest_res_genus2[[2]] %>% head(10)
ttest_res_genus2_clust2_top10$phylum = factor(ttest_res_genus2_clust2_top10$phylum,levels=all_phylums_per_enriched_genus)
g2_colored = ttest_res_genus2_clust2_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g2_colored)
dev.off()
pdf("genus_cluster3_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust3_top10 = ttest_res_genus2[[3]] %>% head(10)
ttest_res_genus2_clust3_top10$phylum = factor(ttest_res_genus2_clust3_top10$phylum,levels=all_phylums_per_enriched_genus)
g3_colored = ttest_res_genus2_clust3_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g3_colored)
dev.off()
pdf("genus_cluster4_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust4_top10 = ttest_res_genus2[[4]] %>% head(10)
ttest_res_genus2_clust4_top10$phylum = factor(ttest_res_genus2_clust4_top10$phylum,levels=all_phylums_per_enriched_genus)
g4_colored = ttest_res_genus2_clust4_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g4_colored)
dev.off()
pdf("genus_cluster5_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust5_top10 = ttest_res_genus2[[5]] %>% head(10)
ttest_res_genus2_clust5_top10$phylum = factor(ttest_res_genus2_clust5_top10$phylum,levels=all_phylums_per_enriched_genus)
g5_colored = ttest_res_genus2_clust5_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g5_colored)
dev.off()
pdf("genus_cluster6_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust6_top10 = ttest_res_genus2[[6]] %>% head(10)
ttest_res_genus2_clust6_top10$phylum = factor(ttest_res_genus2_clust6_top10$phylum,levels=all_phylums_per_enriched_genus)
g6_colored = ttest_res_genus2_clust6_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g6_colored)
dev.off()
pdf("genus_cluster7_one_sided_colored_enrichment_ttest.pdf",width=2.65,height=1.15)
ttest_res_genus2_clust7_top10 = ttest_res_genus2[[7]] %>% head(10)
ttest_res_genus2_clust7_top10$phylum = factor(ttest_res_genus2_clust7_top10$phylum,levels=all_phylums_per_enriched_genus)
g7_colored = ttest_res_genus2_clust7_top10 %>% ggplot(aes(x=reorder(taxa,logFC),y=logFC,fill=phylum)) + geom_bar(stat="identity") + coord_flip() + ylab("") + xlab("") + scale_y_continuous(limits = c(0, 11)) + theme_classic() + theme(axis.text.x = element_text(size=4), axis.text.y = element_text(size=7)) + scale_fill_manual(values=my_colors) + theme(legend.position="none")
print(g7_colored)
dev.off()
```




